textos = [
    # FINANCEIRO (Palavras-chave: boleto, pagamento, nota fiscal, fatura, reembolso, caixa, orçamento)
    "Segue em anexo a nota fiscal para pagamento imediato.",
    "O boleto da prestação de serviços vence amanhã.",
    "Solicito o reembolso das despesas de viagem conforme recibos.",
    "Houve um erro no processamento do extrato bancário deste mês.",
    "A planilha de fluxo de caixa foi atualizada no drive.",
    "Precisamos aprovar o orçamento anual da diretoria.",
    "O pagamento do fornecedor de software está atrasado.",
    "Favor enviar o comprovante de transferência da taxa de serviço.",
    "A segunda via do boleto bancário já está disponível no portal.",
    "A fatura do cartão corporativo precisa ser paga hoje.",
    "O departamento financeiro aprovou o reembolso solicitado.",
    "Nota fiscal de entrada com valor divergente do pedido.",
    "Precisamos revisar o fluxo de caixa para o próximo trimestre.",
    "O pagamento dos impostos foi agendado para sexta-feira.",
    "O extrato de contas a pagar mostra pendências antigas.",
    "Solicito o fechamento do balancete mensal para auditoria financeira.",

    # TÉCNICO (Palavras-chave: servidor, erro, sistema, configuração, banco de dados, rede, manutenção, acesso)
    "o servidor de banco de dados apresentou instabilidade às 14h.",
    "A API de integração parou de responder às requisições.",
    "Necessário realizar a manutenção preventiva no maquinário.",
    "O código apresenta um erro de sintaxe na linha 45 do script.",
    "Solicito a troca do disco rígido do computador da recepção.",
    "O sistema de resfriamento está operando acima da temperatura ideal.",
    "A atualização do firmware corrigiu os bugs de conexão.",
    "Preciso de acesso SSH para configurar o novo ambiente de teste.",
    "O servidor web caiu e precisa de reinicialização imediata.",
    "Erro crítico de sistema detectado no servidor de arquivos.",
    "Configuração de rede necessária para o novo roteador wi-fi.",
    "Manutenção técnica agendada para os servidores da nuvem.",
    "O suporte técnico resolveu o problema de acesso ao sistema.",
    "Falha na conexão com o banco de dados principal da aplicação.",
    "A placa-mãe do servidor apresenta sinal de superaquecimento.",
    "Necessário atualizar o driver da placa de rede para corrigir erro.",

    # ADMINISTRATIVO (Palavras-chave: reunião, sala, ata, contrato, escritório, documentos, escala, fornecedor)
    "A reunião de condomínio foi agendada para sexta-feira.",
    "Favor reservar a sala de reuniões principal para o período da tarde.",
    "A ata da última assembleia já está disponível para assinatura.",
    "Solicito a renovação do estoque de material de escritório.",
    "O contrato de aluguel da sede precisa ser revisado este mês.",
    "Favor organizar os documentos da recepção em pastas suspensas.",
    "A escala de folgas dos funcionários sofreu alterações.",
    "Precisamos de um novo fornecedor de café para a copa.",
    "Agendamento de sala para treinamento interno na quarta-feira.",
    "O contrato de prestação de serviços administrativos foi renovado.",
    "Documentos para arquivo morto devem ser levados ao depósito.",
    "Favor solicitar orçamento de novos móveis para o escritório.",
    "A reunião de diretoria foi cancelada por falta de quórum.",
    "O inventário de bens móveis da sede está desatualizado.",
    "Organização da agenda da presidência para a próxima semana.",
    "Solicito a compra de papel sulfite e toners para o escritório.",

    # RH (Palavras-chave: seletivo, colaborador, folha de pagamento, treinamento, férias, plano de saúde, feedback, benefício)
    "O processo seletivo para a vaga de analista começa na segunda.",
    "Favor enviar os documentos para admissão do novo colaborador.",
    "A folha de pagamento será fechada no dia 25.",
    "Agendamos o treinamento de segurança do trabalho para todos.",
    "Solicito o histórico de férias do departamento de vendas.",
    "O plano de saúde terá reajuste na próxima mensalidade.",
    "Favor realizar a integração dos novos estagiários.",
    "O feedback da avaliação de desempenho foi enviado por e-mail.",
    "Recrutamento e seleção de novos talentos para o RH.",
    "O colaborador solicitou desligamento por motivos pessoais.",
    "Processo de promoção interna para gerente de projetos.",
    "Benefícios corporativos incluem vale-transporte e alimentação.",
    "Treinamento de liderança para novos supervisores de área.",
    "A folha de ponto deve ser assinada até o quinto dia útil.",
    "O holerite do mês passado está com erro no cálculo do FGTS.",
    "Entrevista com o candidato aprovado na primeira fase do seletivo.",

    # COMERCIAL (Palavras-chave: cliente, desconto, venda, proposta, comercial, lead, meta, relatório)
    "O cliente solicitou um desconto de 10% no fechamento do pedido.",
    "A proposta comercial foi enviada e aguarda aprovação.",
    "Temos uma nova oportunidade de venda para a conta estratégica.",
    "Favor entrar em contato com o lead interessado no serviço.",
    "A meta de vendas do mês foi atingida com antecedência.",
    "O contrato com o novo parceiro foi assinado hoje.",
    "Solicito o relatório de vendas por região do último semestre.",
    "O cliente cancelou a demonstração agendada para amanhã.",
    "Negociação de preços com o cliente da conta premium.",
    "O pipeline de vendas mostra um aumento na conversão de leads.",
    "Envio de proposta revisada com novos prazos de entrega.",
    "A equipe comercial participará da feira de negócios nacional.",
    "O faturamento de vendas superou as expectativas do mês.",
    "Visita técnica ao cliente para fechamento de contrato anual.",
    "Relatório mensal de desempenho da equipe de vendas externas.",
    "Prospectar novos leads no setor de tecnologia e inovação.",

    # MARKETING (Palavras-chave: campanha, engajamento, site, tráfego, anúncios, marca, artes, e-mail marketing)
    "A nova campanha nas redes sociais gerou um alto engajamento.",
    "Precisamos aprovar a arte do banner para o evento de TI.",
    "O tráfego orgânico do site cresceu 15% nas últimas semanas.",
    "Favor revisar o texto do blog post sobre inteligência artificial.",
    "O investimento em anúncios no Google será triplicado.",
    "A identidade visual da marca precisa de pequenos ajustes.",
    "O relatório de métricas do Instagram está pronto para análise.",
    "Precisamos de sugestões de frases para o e-mail marketing.",
    "Criação de artes para a campanha de black friday.",
    "O engajamento no Facebook caiu após a última atualização.",
    "Análise de SEO para melhorar o posicionamento do site.",
    "O cronograma de postagens no LinkedIn está atrasado.",
    "Precisamos contratar uma agência de marketing digital.",
    "O branding da empresa passará por uma reformulação total.",
    "Otimização de anúncios para reduzir o custo por clique.",
    "Favor agendar o envio da newsletter semanal por e-mail.",

    # JURÍDICO (Palavras-chave: processo, judicial, contrato, cláusula, procuração, intimação, parecer, jurídico)
    "O processo judicial entrou em fase de execução de sentença.",
    "Favor analisar as cláusulas de rescisão do contrato de prestação.",
    "A procuração precisa ser reconhecida em cartório com urgência.",
    "Houve uma intimação para prestar esclarecimentos sobre o caso.",
    "O parecer jurídico sobre a nova lei foi concluído.",
    "Precisamos de uma cópia autenticada do estatuto social.",
    "O acordo extrajudicial foi aceito por ambas as partes.",
    "Favor verificar a conformidade com a LGPD no formulário do site.",
    "Contrato jurídico revisado com foco nas cláusulas de multa.",
    "O advogado solicitou o desarquivamento do processo cível.",
    "Parecer legal sobre os riscos de patentes da nova marca.",
    "Ação judicial contra o fornecedor por quebra de contrato.",
    "Documentação jurídica enviada para o fórum da comarca.",
    "Revisão de cláusulas contratuais para evitar bitributação.",
    "Intimação recebida para audiência de conciliação trabalhista.",
    "Análise jurídica sobre as novas normas da legislação tributária.",

    # PROJETOS (Palavras-chave: cronograma, projeto, sprint, requisitos, stakeholders, kickoff, escopo, deadline)
    "O cronograma do projeto sofreu um atraso de duas semanas.",
    "A sprint foi finalizada e os requisitos foram entregues.",
    "Precisamos definir os stakeholders para a fase de testes.",
    "O gráfico de burndown mostra que estamos dentro do prazo.",
    "Solicito a alocação de mais um desenvolvedor para este projeto.",
    "A reunião de kickoff será realizada via chamada de vídeo.",
    "O escopo do projeto precisa ser reavaliado pela diretoria.",
    "O encerramento do projeto está previsto para o final do mês.",
    "Planejamento do projeto de expansão para o próximo ano.",
    "O gerente de projetos solicitou a lista de pendências da sprint.",
    "Definição de marcos e entregáveis para o novo cronograma.",
    "Os stakeholders aprovaram a mudança no escopo inicial.",
    "Acompanhamento semanal do projeto através do gráfico gantt.",
    "O deadline final do projeto não pode ser postergado.",
    "Apresentação dos resultados da primeira etapa do projeto.",
    "Reunião de retrospectiva da sprint com toda a equipe técnica.",

    # LOGÍSTICA (Palavras-chave: carga, estoque, entrega, frete, transportadora, caminhão, armazém, rastreio)
    "A carga foi despachada e o código de rastreio já está ativo.",
    "O estoque de produtos acabados está abaixo do nível crítico.",
    "Houve um atraso na entrega devido a bloqueios na rodovia.",
    "Favor conferir a romaneio de carga que chegou no depósito.",
    "A rota de entrega foi otimizada para reduzir o consumo de diesel.",
    "O caminhão está aguardando liberação na doca de carregamento.",
    "Solicito o inventário atualizado das prateleiras do setor B.",
    "A transportadora enviou uma nova tabela de fretes para o sul.",
    "Logística reversa aplicada aos produtos devolvidos pelos clientes.",
    "O carregamento da carga pesada deve ser feito no período noturno.",
    "Frete internacional com custos elevados devido ao câmbio.",
    "O armazém central atingiu a capacidade máxima de estoque.",
    "Sistema de rastreio em tempo real para as entregas urbanas.",
    "O romaneio de saída deve ser assinado pelo motorista do caminhão.",
    "Conferência de mercadorias no recebimento do depósito central.",
    "Otimização do espaço no estoque para a chegada da nova carga.",

    # ARQUIVO HISTÓRICO (Palavras-chave: histórico, documentos antigos, digitalizados, registro, acervo, década, fotos)
    "Localizamos as fotos da fundação da empresa em 1980.",
    "Os documentos antigos foram digitalizados para preservação.",
    "Este registro contém as primeiras atas assinadas pelos sócios.",
    "O jornal da época relata a expansão da fábrica original.",
    "Solicito a catalogação dos manuscritos encontrados no porão.",
    "A caixa 45 contém a correspondência oficial da década de 90.",
    "O acervo físico precisa de controle de umidade e temperatura.",
    "Encontramos o projeto arquitetônico da primeira sede da marca.",
    "Histórico de fundação da empresa recuperado em arquivos físicos.",
    "Digitalização de registros de funcionários da década de 70.",
    "Fotos antigas da primeira sede foram restauradas para o museu.",
    "O arquivo histórico preserva a memória institucional do grupo.",
    "Documentos de registro de patentes antigas foram catalogados.",
    "O acervo de correspondências contém cartas dos fundadores.",
    "Preservação de registros históricos contra ação do tempo.",
    "Exposição de fotos e documentos do arquivo histórico da firma."
]