textos = [
    # FINANCEIRO
    "Segue em anexo a nota fiscal para pagamento imediato.", "O boleto da prestação de serviços vence amanhã.",
    "Solicito o reembolso das despesas de viagem conforme recibos.", "Houve um erro no processamento do extrato bancário deste mês.",
    "A planilha de fluxo de caixa foi atualizada no drive.", "Precisamos aprovar o orçamento anual da diretoria.",
    "O pagamento do fornecedor de software está atrasado.", "Favor enviar o comprovante de transferência da taxa de serviço.",
    "A segunda via do boleto bancário já está disponível no portal.", "A fatura do cartão corporativo precisa ser paga hoje.",
    "O departamento financeiro aprovou o reembolso solicitado.", "Nota fiscal de entrada com valor divergente do pedido.",
    "Precisamos revisar o fluxo de caixa para o próximo trimestre.", "O pagamento dos impostos foi agendado para sexta-feira.",
    "O extrato de contas a pagar mostra pendências antigas.", "Solicito o fechamento do balancete mensal para auditoria financeira.",
    "Identificamos uma duplicidade no pagamento da fatura de energia.", "O relatório de inadimplência aponta necessidade de cobrança ativa.",
    "Favor emitir a nota fiscal de serviços referente ao projeto Alpha.", "O aporte financeiro para novos investimentos foi autorizado.",
    "Necessário conciliação bancária das contas correntes da matriz.", "A auditoria externa solicitou os comprovantes de despesas miúdas.",
    "O limite do cartão de crédito empresarial foi atingido.", "Revisão das taxas de juros incidentes sobre o financiamento atual.",
    "Provisionamento de fundos para o pagamento do décimo terceiro.", "O setor de contas a receber confirmou o depósito do cliente.",
    "Atualização da tabela de preços devido à variação do câmbio.", "A análise de crédito do novo parceiro comercial foi negada.",
    "Transferência entre contas para cobertura de saldo devedor.", "O custo fixo operacional subiu acima do orçado para o mês.",
    "Solicitação de prorrogação de prazo para o boleto do fornecedor.", "O balanço patrimonial consolidado está pronto para assinatura.",

    # TÉCNICO
    "o servidor de banco de dados apresentou instabilidade às 14h.", "A API de integração parou de responder às requisições.",
    "Necessário realizar a manutenção preventiva no maquinário.", "O código apresenta um erro de sintaxe na linha 45 do script.",
    "Solicito a troca do disco rígido do computador da recepção.", "O sistema de resfriamento está operando acima da temperatura ideal.",
    "A atualização do firmware corrigiu os bugs de conexão.", "Preciso de acesso SSH para configurar o novo ambiente de teste.",
    "O servidor web caiu e precisa de reinicialização imediata.", "Erro crítico de sistema detectado no servidor de arquivos.",
    "Configuração de rede necessária para o novo roteador wi-fi.", "Manutenção técnica agendada para os servidores da nuvem.",
    "O suporte técnico resolveu o problema de acesso ao sistema.", "Falha na conexão com o banco de dados principal da aplicação.",
    "A placa-mãe do servidor apresenta sinal de superaquecimento.", "Necessário atualizar o driver da placa de rede para corrigir erro.",
    "O firewall está bloqueando o tráfego na porta 8080 do servidor.", "Necessário realizar o deploy da nova versão no ambiente de produção.",
    "O backup automatizado falhou devido à falta de espaço no storage.", "Implementação de autenticação em dois fatores no sistema interno.",
    "A latência da rede está prejudicando a performance do banco.", "Migração de dados para a nova estrutura de tabelas relacionais.",
    "O log de erros aponta falha na autenticação do usuário admin.", "Substituição preventiva dos cabos de fibra óptica do rack central.",
    "O sistema ERP está travando durante a geração de relatórios pesados.", "Configuração de ambiente Docker para os novos desenvolvedores.",
    "Monitoramento de rede detectou uma tentativa de acesso não autorizada.", "O certificado SSL do domínio expirou e precisa de renovação.",
    "Instalação de patches de segurança no sistema operacional Linux.", "O hardware do switch apresentou falha física nas portas de entrada.",
    "Otimização de consultas SQL para reduzir o tempo de resposta.", "Necessário formatar a estação de trabalho do setor de design.",

    # ADMINISTRATIVO
    "A reunião de condomínio foi agendada para sexta-feira.", "Favor reservar a sala de reuniões principal para o período da tarde.",
    "A ata da última assembleia já está disponível para assinatura.", "Solicito a renovação do estoque de material de escritório.",
    "O contrato de aluguel da sede precisa ser revisado este mês.", "Favor organizar os documentos da recepção em pastas suspensas.",
    "A escala de folgas dos funcionários sofreu alterações.", "Precisamos de um novo fornecedor de café para a copa.",
    "Agendamento de sala para treinamento interno na quarta-feira.", "O contrato de prestação de serviços administrativos foi renovado.",
    "Documentos para arquivo morto devem ser levados ao depósito.", "Favor solicitar orçamento de novos móveis para o escritório.",
    "A reunião de diretoria foi cancelada por falta de quórum.", "O inventário de bens móveis da sede está desatualizado.",
    "Organização da agenda da presidência para a próxima semana.", "Solicito a compra de papel sulfite e toners para o escritório.",
    "A copeira informou que os insumos de limpeza estão acabando.", "Necessário providenciar a manutenção do ar-condicionado da recepção.",
    "Favor digitalizar os documentos e enviá-los para a contabilidade.", "A recepção precisa de uma nova lista de ramais atualizada.",
    "O crachá do novo funcionário deve ser solicitado à portaria.", "Agendamento de viagem e reserva de hotel para o diretor.",
    "Necessário organizar o estacionamento para os visitantes da feira.", "A política interna de uso dos carros da empresa foi revisada.",
    "Favor conferir a entrega da papelaria e assinar o canhoto.", "O serviço de motoboy deve ser agendado com duas horas de antecedência.",
    "Relatório de gastos com combustível da frota administrativa.", "O mural de avisos precisa ser atualizado com as novas normas.",
    "Contratação de serviço de dedetização para o próximo sábado.", "Organização do coquetel de encerramento do projeto trimestral.",
    "A chave da sala de arquivos sumiu e precisamos de uma cópia.", "Verificação das luzes de emergência e extintores do prédio.",

    # RH
    "O processo seletivo para a vaga de analista começa na segunda.", "Favor enviar os documentos para admissão do novo colaborador.",
    "A folha de pagamento será fechada no dia 25.", "Agendamos o treinamento de segurança do trabalho para todos.",
    "Solicito o histórico de férias do departamento de vendas.", "O plano de saúde terá reajuste na próxima mensalidade.",
    "Favor realizar a integração dos novos estagiários.", "O feedback da avaliação de desempenho foi enviado por e-mail.",
    "Recrutamento e seleção de novos talentos para o RH.", "O colaborador solicitou desligamento por motivos pessoais.",
    "Processo de promoção interna para gerente de projetos.", "Benefícios corporativos incluem vale-transporte e alimentação.",
    "Treinamento de liderança para novos supervisores de área.", "A folha de ponto deve ser assinada até o quinto dia útil.",
    "O holerite do mês passado está com erro no cálculo do FGTS.", "Entrevista com o candidato aprovado na primeira fase do seletivo.",
    "Publicação de vaga de emprego no LinkedIn e portais parceiros.", "Análise de clima organizacional aponta necessidade de melhorias.",
    "O colaborador apresentou atestado médico de cinco dias.", "Necessário agendar o exame admissional para o novo contratado.",
    "O bônus por meta atingida será pago na folha complementar.", "Revisão do plano de cargos e salários para o próximo ano.",
    "O setor de treinamento preparou um novo curso de LGPD.", "Entrega de kits de boas-vindas para os novos funcionários.",
    "A política de home office foi alterada pela gestão de pessoas.", "Entrevista de desligamento realizada com o analista sênior.",
    "Convocação para a CIPA e eleição dos novos representantes.", "O seguro de vida corporativo agora tem novas coberturas.",
    "O RH está organizando o evento de confraternização anual.", "Necessário atualizar o cadastro de dependentes para o convênio.",
    "O feedback 360 graus será aplicado em todos os níveis.", "Cálculo de rescisão contratual enviado para homologação.",

    # COMERCIAL
    "O cliente solicitou um desconto de 10% no fechamento do pedido.", "A proposta comercial foi enviada e aguarda aprovação.",
    "Temos uma nova oportunidade de venda para a conta estratégica.", "Favor entrar em contato com o lead interessado no serviço.",
    "A meta de vendas do mês foi atingida com antecedência.", "O contrato com o novo parceiro foi assinado hoje.",
    "Solicito o relatório de vendas por região do último semestre.", "O cliente cancelou a demonstração agendada para amanhã.",
    "Negociação de preços com o cliente da conta premium.", "O pipeline de vendas mostra um aumento na conversão de leads.",
    "Envio de proposta revisada com novos prazos de entrega.", "A equipe comercial participará da feira de negócios nacional.",
    "O faturamento de vendas superou as expectativas do mês.", "Visita técnica ao cliente para fechamento de contrato anual.",
    "Relatório mensal de desempenho da equipe de vendas externas.", "Prospectar novos leads no setor de tecnologia e inovação.",
    "O CRM está com dados desatualizados sobre o cliente X.", "Apresentação comercial marcada para o novo grupo de investidores.",
    "Necessário elaborar um plano de ação para reverter a perda de contas.", "O ticket médio das vendas subiu após a nova estratégia.",
    "Follow-up com os clientes que receberam orçamento semana passada.", "O diretor comercial solicitou a previsão de vendas para o trimestre.",
    "Abertura de novos canais de distribuição para o produto varejo.", "O treinamento de técnicas de fechamento será na terça-feira.",
    "Análise de concorrência mostra que nossos prazos estão competitivos.", "Campanha de incentivo para vendedores com melhor performance.",
    "O suporte comercial deve auxiliar na elaboração de contratos.", "Reativação de clientes inativos através de ofertas especiais.",
    "O fechamento da venda depende da aprovação do limite de crédito.", "A equipe de pré-vendas qualificou dez novos leads hoje.",
    "Ajuste na comissão dos representantes comerciais externos.", "Elaboração de catálogo de produtos atualizado para os clientes.",

    # MARKETING
    "A nova campanha nas redes sociais gerou um alto engajamento.", "Precisamos aprovar a arte do banner para o evento de TI.",
    "O tráfego orgânico do site cresceu 15% nas últimas semanas.", "Favor revisar o texto do blog post sobre inteligência artificial.",
    "O investimento em anúncios no Google será triplicado.", "A identidade visual da marca precisa de pequenos ajustes.",
    "O relatório de métricas do Instagram está pronto para análise.", "Precisamos de sugestões de frases para o e-mail marketing.",
    "Criação de artes para a campanha de black friday.", "O engajamento no Facebook caiu após a última atualização.",
    "Análise de SEO para melhorar o posicionamento do site.", "O cronograma de postagens no LinkedIn está atrasado.",
    "Precisamos contratar uma agência de marketing digital.", "O branding da empresa passará por uma reformulação total.",
    "Otimização de anúncios para reduzir o custo por clique.", "Favor agendar o envio da newsletter semanal por e-mail.",
    "O lançamento do novo produto terá um evento presencial.", "Monitoramento da marca aponta menções positivas no Twitter.",
    "A estratégia de marketing de influência está trazendo novos usuários.", "Necessário criar um roteiro para o vídeo institucional.",
    "A taxa de abertura dos e-mails promocionais está baixa.", "Ajuste no design da landing page para aumentar a conversão.",
    "O setor de criação precisa de um novo briefing para a campanha.", "Análise do funil de marketing e comportamento do usuário no site.",
    "Patrocínio de evento esportivo para fortalecer o branding.", "Otimização de palavras-chave para a campanha de pesquisa paga.",
    "Criação de materiais para PDV e pontos de venda físicos.", "A assessoria de imprensa enviou o clipping da semana.",
    "Desenvolvimento de peças publicitárias para anúncios em rádio.", "O teste A/B no site mostrou preferência pelo layout azul.",
    "Produção de conteúdo para o canal da empresa no YouTube.", "O ROI das campanhas de tráfego pago subiu consideravelmente.",

    # JURÍDICO
    "O processo judicial entrou em fase de execução de sentença.", "Favor analisar as cláusulas de rescisão do contrato de prestação.",
    "A procuração precisa ser reconhecida em cartório com urgência.", "Houve uma intimação para prestar esclarecimentos sobre o caso.",
    "O parecer jurídico sobre a nova lei foi concluído.", "Precisamos de uma cópia autenticada do estatuto social.",
    "O acordo extrajudicial foi aceito por ambas as partes.", "Favor verificar a conformidade com a LGPD no formulário do site.",
    "Contrato jurídico revisado com foco nas cláusulas de multa.", "O advogado solicitou o desarquivamento do processo cível.",
    "Parecer legal sobre os riscos de patentes da nova marca.", "Ação judicial contra o fornecedor por quebra de contrato.",
    "Documentação jurídica enviada para o fórum da comarca.", "Revisão de cláusulas contratuais para evitar bitributação.",
    "Intimação recebida para audiência de conciliação trabalhista.", "Análise jurídica sobre as novas normas da legislação tributária.",
    "O jurídico barrou a campanha por risco de direitos autorais.", "Elaboração de termo de confidencialidade (NDA) para o novo projeto.",
    "Contestação judicial enviada dentro do prazo legal estabelecido.", "Acompanhamento de perícia técnica em processo de danos morais.",
    "O setor de compliance revisou o código de conduta ética.", "Necessário registrar a marca no INPI para proteção legal.",
    "O contrato de parceria internacional precisa de tradução juramentada.", "Reunião com o escritório de advocacia externo para estratégia.",
    "Verificação de certidões negativas de débito para licitação.", "Análise de riscos contratuais em editais públicos de compra.",
    "O departamento jurídico autorizou o termo de quitação.", "A defesa na ação de pequenas causas foi devidamente protocolada.",
    "Parecer sobre a viabilidade jurídica da fusão entre empresas.", "O oficial de justiça entregou a notificação para a diretoria.",
    "Renovação de procurações de plenos poderes para os sócios.", "Criação de novos termos de uso e política de privacidade.",

    # PROJETOS
    "O cronograma do projeto sofreu um atraso de duas semanas.", "A sprint foi finalizada e os requisitos foram entregues.",
    "Precisamos definir os stakeholders para a fase de testes.", "O gráfico de burndown mostra que estamos dentro do prazo.",
    "Solicito a alocação de mais um desenvolvedor para este projeto.", "A reunião de kickoff será realizada via chamada de vídeo.",
    "O escopo do projeto precisa ser reavaliado pela diretoria.", "O encerramento do projeto está previsto para o final do mês.",
    "Planejamento do projeto de expansão para o próximo ano.", "O gerente de projetos solicitou a lista de pendências da sprint.",
    "Definição de marcos e entregáveis para o novo cronograma.", "Os stakeholders aprovaram a mudança no escopo inicial.",
    "Acompanhamento semanal do projeto através do gráfico gantt.", "O deadline final do projeto não pode ser postergado.",
    "Apresentação dos resultados da primeira etapa do projeto.", "Reunião de retrospectiva da sprint com toda a equipe técnica.",
    "O projeto de infraestrutura foi pausado por falta de recursos.", "Realização de workshop de design thinking com o time de produtos.",
    "Gestão de riscos do projeto aponta falhas na entrega de hardware.", "Necessário atualizar o backlog do Jira para a próxima iteração.",
    "O reporte de status semanal foi enviado para os patrocinadores.", "Reunião de alinhamento entre o time de dev e o time de design.",
    "O MVP do sistema foi lançado para um grupo de usuários beta.", "Mudança nas prioridades da sprint devido a um bug crítico.",
    "Criação da WBS (estrutura analítica) para o novo projeto de rede.", "O orçamento do projeto excedeu a margem de segurança prevista.",
    "Aprovação técnica final para o encerramento da fase de testes.", "O scrum master facilitou a reunião diária de 15 minutos.",
    "Definição de indicadores de desempenho (KPIs) para o projeto.", "A equipe de QA encontrou impedimentos no ambiente de homologação.",
    "Entrega da documentação técnica e manuais do usuário final.", "O comitê de projetos aprovou a continuidade do cronograma.",

    # LOGÍSTICA
    "A carga foi despachada e o código de rastreio já está ativo.", "O estoque de produtos acabados está abaixo do nível crítico.",
    "Houve um atraso na entrega devido a bloqueios na rodovia.", "Favor conferir a romaneio de carga que chegou no depósito.",
    "A rota de entrega foi otimizada para reduzir o consumo de diesel.", "O caminhão está aguardando liberação na doca de carregamento.",
    "Solicito o inventário atualizado das prateleiras do setor B.", "A transportadora enviou uma nova tabela de fretes para o sul.",
    "Logística reversa aplicada aos produtos devolvidos pelos clientes.", "O carregamento da carga pesada deve ser feito no período noturno.",
    "Frete internacional com custos elevados devido ao câmbio.", "O armazém central atingiu a capacidade máxima de estoque.",
    "Sistema de rastreio em tempo real para as entregas urbanas.", "O romaneio de saída deve ser assinado pelo motorista do caminhão.",
    "Conferência de mercadorias no recebimento do depósito central.", "Otimização do espaço no estoque para a chegada da nova carga.",
    "A expedição informou que o pedido está pronto para coleta.", "Avaria detectada no carregamento de materiais frágeis.",
    "O custo logístico por pedido aumentou no último período.", "Necessário contratar novos motoristas agregados para a demanda.",
    "O centro de distribuição operará em regime de plantão no feriado.", "A paletização das mercadorias deve seguir o padrão de altura.",
    "O tempo médio de entrega (lead time) caiu para dois dias.", "Monitoramento de frotas via satélite para garantir a segurança.",
    "O fornecedor atrasou a entrega da matéria-prima no armazém.", "Criação de um novo hub logístico na região nordeste do país.",
    "O fluxo de entrada e saída de veículos foi reorganizado.", "Necessário realizar a manutenção das empilhadeiras do estoque.",
    "A nota fiscal de transporte (CT-e) foi emitida corretamente.", "Controle de qualidade realizado na conferência cega do estoque.",
    "Sinalização das áreas de risco dentro do galpão de logística.", "O frete fracionado é a melhor opção para pequenos envios.",

    # ARQUIVO HISTÓRICO
    "Localizamos as fotos da fundação da empresa em 1980.", "Os documentos antigos foram digitalizados para preservação.",
    "Este registro contém as primeiras atas assinadas pelos sócios.", "O jornal da época relata a expansão da fábrica original.",
    "Solicito a catalogação dos manuscritos encontrados no porão.", "A caixa 45 contém a correspondência oficial da década de 90.",
    "O acervo físico precisa de controle de umidade e temperatura.", "Encontramos o projeto arquitetônico da primeira sede da marca.",
    "Histórico de fundação da empresa recuperado em arquivos físicos.", "Digitalização de registros de funcionários da década de 70.",
    "Fotos antigas da primeira sede foram restauradas para o museu.", "O arquivo histórico preserva a memória institucional do grupo.",
    "Documentos de registro de patentes antigas foram catalogados.", "O acervo de correspondências contém cartas dos fundadores.",
    "Preservação de registros históricos contra ação do tempo.", "Exposição de fotos e documentos do arquivo histórico da firma.",
    "Encontramos o primeiro logotipo desenhado à mão em 1950.", "A coleção de medalhas e prêmios da empresa foi higienizada.",
    "Relatos de antigos funcionários foram gravados para o acervo.", "Digitalização das plantas originais das instalações industriais.",
    "O livro de visitas da inauguração da filial contém nomes ilustres.", "Pesquisa histórica sobre a origem da marca e seus fundadores.",
    "O setor de arquivo recebeu doação de fotos da década de 60.", "Necessário restaurar o papel das primeiras escrituras de compra.",
    "O acervo digital agora conta com vídeos das primeiras propagandas.", "Organização cronológica das notícias de jornal sobre a empresa.",
    "A história da empresa foi compilada em um livro comemorativo.", "Documentos diplomáticos de parcerias antigas foram encontrados.",
    "Limpeza técnica para remoção de fungos em documentos de papel.", "A árvore genealógica da família fundadora está no arquivo.",
    "Recuperação de dados de fitas magnéticas obsoletas do acervo.", "Identificação de personagens em fotos de eventos da década de 40."
]